services:
  pet-db:
    container_name: pet-db
    build:
      context: pet-db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${PET_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PET_MYSQL_DATABASE}
      MYSQL_USER: ${PET_MYSQL_USER}
      MYSQL_PASSWORD: ${PET_MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "pet-db" ]
      retries: 1
    ports:
      - ${PET_MYSQL_PORT}:3306

  shelter-db:
    container_name: shelter-db
    build:
      context: shelter-db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${SHELTER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${SHELTER_POSTGRES_USER}
      POSTGRES_DB: ${SHELTER_POSTGRES_DB}
    depends_on:
      pet-db:
        condition: "service_healthy"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${SHELTER_POSTGRES_USER} -d ${SHELTER_POSTGRES_DB}'" ]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - ${SHELTER_POSTGRES_PORT}:5432

  metrics-db:
    container_name: metrics-db
    build:
      context: metrics-db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${METRICS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${METRICS_MYSQL_DATABASE}
      MYSQL_USER: ${METRICS_MYSQL_USER}
      MYSQL_PASSWORD: ${METRICS_MYSQL_PASSWORD}
    depends_on:
      shelter-db:
        condition: "service_healthy"
      pet-db:
        condition: "service_healthy"
    ports:
      - ${METRICS_MYSQL_PORT}:3306